# 下面这两个是从 Google Cloud Console 新申请的 OAuth 2.0 Client ID
GOOGLE_CLIENT_ID = "95257762932-hlc7v0qrkauimq219vbauqonm6tqbc18.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

# 这个是告诉谷歌登录成功后跳回哪里
GOOGLE_REDIRECT_URI = "http://localhost:8501"

# 这个是数据库地址，如果你暂时没有云数据库，就用下面这一行（本地模式）
DATABASE_URL = "sqlite:///splitwise_pro.db"